# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:11.6-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data

    ports:
      - ${POSTGRES_PORT}:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080